//Videos Constants
export const GET_VIDEOS_REQUEST = 'GET_VIDEOS_REQUEST';
export const GET_VIDEOS_REQUEST_SUCCESS = 'GET_VIDEOS_REQUEST_SUCCESS';
export const GET_VIDEOS_REQUEST_ERROR = 'GET_VIDEOS_REQUEST_ERROR';

//Map Constants
export const CHANGE_LOCATION = 'CHANGE_LOCATION';
